[package]
name = "callee"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
pinocchio = { workspace = true }
pinocchio-system = "0.3.0"

[dev-dependencies]
mollusk-svm = { workspace = true }
solana-sdk = { workspace = true }