[package]
name = "caller"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pinocchio = { workspace = true }
pinocchio-pubkey = "0.3.0"

[dev-dependencies]
mollusk-svm = { workspace = true }
solana-sdk = { workspace = true }